### ISSUE TITLE
Error in event_log and data_log modules

### ISSUE THREAD

**Issue by hemanandsamba** [EGuthrieWasTaken/tlnetcard_python#5]
```
>pip freeze
certifi==2020.12.5
chardet==3.0.4
idna==2.10
ply==3.11
pyasn1==0.4.8
pycryptodomex==3.9.9
pysmi==0.3.4
pysnmp==4.4.12
requests==2.23.0
selenium==3.141.0
tlnetcard-python==0.3.2
typing==3.7.4.1
urllib3==1.26.2
```
The following line appears in history/configure/configure.py, history/event_log/event_log.py and history/data_log/data_log.py:
```
self._post_url = self._login_object.get_base_url + "/delta/hist_data"
```
When it should be:
```
self._post_url = self._login_object.get_base_url() + "/delta/hist_data"
```
I ran into this when trying the examples in the documentation. Interestingly, the examples did not run into the issue in the configure.py file.

**Comment by EGuthrieWasTaken** [comment]
Hello @hemanandsamba! Thank you for pointing out this error! I have rectified the error in the source code that you pointed out, and have updated the package on PyPi (0.3.3).
